logs:
    - name: root
      level: info
      formatter: '%d%T%m%n'
      appenders:
          - type: FileLog
            file: root.txt
          - type: ConsoleLog

    - name: system
      level: debug
      formatter: '%d%T%m%n'
      appenders:
          - type: FileLog
            file: system.txt
            formatter: '%d%T[%p]%T%m%n'
          - type: ConsoleLog  

# system:
#     port: 9900
#     value: 15.0
#     int_vec: [10, 20]
#     int_list: [20, 40, 50]
#     int_set: [30, 20, 60]
#     int_uset: [30, 20, 60]
#     str_int_map:
#       k: 30
#       k2: 20
#       k3: 10
#     str_int_umap:
#       k: 130
#       k2: 120
#       k3: 110

# class:
#     Person:
#       name: SzQ
#       age: 25
#       sex: true
#     map:
#       person1:
#         name: szq1
#         age: 25
#         sex: false
#       person2:
#         name: szq2
#         age: 26
#         sex: true