http_servers:
    - address: ["0.0.0.0:8080"]
      keepalive: 1
      timeout: 1000
      name: TinyServer/1.1

    - address: ["0.0.0.0:8070"]
      keepalive: 1
      timeout: 1000
      name: TinyServer/2.1